uiRF: 
	# Running the GUI program - Random Forest
	python3 src/main.py gui RF
trainRF:
	# Training the model - Random Forest
	python3 src/main.py train RF
uiNN: 
	# Running the GUI program - Neural Network
	python3 src/main.py gui NN
trainNN:
	# Training the model - Neural Network
	python3 src/main.py train NN
c-All:
	# Compilling all files 
	python3 -m compileall .
