uiRF: 
	# Running the GUI program
	python3 src/main.py gui RF
trainRF:
	# Training the model
	python3 src/main.py train RF
uiNN: 
	# Running the GUI program
	python3 src/main.py gui NN
trainNN:
	# Training the model
	python3 src/main.py train NN
c-All:
	# Running all files 
	python3 -m compileall .
